# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: "0 5 * * 1-5"
  push:
    branches: [ master ]
    paths:
      - "packages/web/**"
  pull_request:
    branches: [ master ]
    paths:
      - "packages/web/**"

jobs:
  build:

    runs-on: ubuntu-latest
    name: web-build
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - run: yarn install
      - run: yarn predeploy
      - run: yarn deploy
