name: web deploy

on:
  push:
    paths:
      - "./packages/web/**"
    branches:
      -master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 12.x]
    
    steps:
      - uses: actions/checkout@v1

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install packages
        run: yarn
      
      - name: deploy to github-pages
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
          git remote set-url origin https://${{ secrets.PERSONAL_TOKEN }}@github.com/${{ secrets.USERNAME }}/${{ secrets.REPO }}.git
          yarn predeploy
          yarn deploy