name: web-deploy

on:
  push:
    paths:
      - "packages/web/**"
    branches:
      - "master"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install node.js & Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Install
        run: yarn
        
      - name: Build
        run: yarn workspace web build
        
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          working-directory: ./packages/web
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
    
