name: web-deploy

on:
  push:
    paths:
      - "packages/web/**"
    branches:
      - "master"
      
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install node.js & Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Install
        run: yarn
        
      - name: Build
        working-directory: ./packages/web
        run: yarn build
        
      - name: Deploy
        working-directory: ./packages/web
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
        
